[server]
scriptfile = "script.py"
root = "files"
address = "0.0.0.0"
port = 6969
timeout = 5
retries = 3

[env]
rambase = "baseaddr"
cmdtftp = "tftpboot"
cmdtftpput = "tftpput"
nfsserver = 'truenas.lan'
rootfs = '/mnt/STORAGE/config/camera/boot/rootfs'

[cam123]
script = "camera_bootstrap"
rambase = "loadaddr"
rootfs = '/mnt/STORAGE/config/camera/boot/rootfs.cam123'

[default]
script = "default"
