[server]
scriptfile = "openipc.py"
rootdir = "/tmp/openipc-tftp"
address = "0.0.0.0"
port = 69
timeout = 5
retries = 3
log_level = "info"
echo_no_newline = "backslash_c" # Use "dash_n" for targets that support `echo -n`.

[env]
rambase    = "baseaddr"
cmdtftp    = "tftpboot"
cmdtftpput = "tftpput"

[default]
entry_func = "default"
