[server]
scriptfile = "../scripts/openipc.py"
rootdir = "/home/elliot/work/openipc/uboot-tftp/files"
address = "0.0.0.0"
port = 69
timeout = 5
retries = 3
log_level = "info"

[env]
rambase    = "baseaddr"
cmdtftp    = "tftpboot"
cmdtftpput = "tftpput"
nfsserver  = 'truenas.lan'
rootfs     = '/mnt/STORAGE/config/camera/boot/rootfs'
kernel     = 'uImage.${soc}'

#[cam123]
#entry_func = "bootnfs"
#rootfs = '/mnt/STORAGE/config/camera/boot/rootfs.cam123'

[default]
entry_func = "default"
